# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: MERN CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]   

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # --- Backend ---
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Run backend tests
        working-directory: ./backend
        run: npm test --if-present

      # --- Frontend (interview-pep) ---
      - name: Install frontend dependencies
        working-directory: ./frontend/interview-pep
        run: npm install

      - name: Run frontend tests
        working-directory: ./frontend/interview-pep
        run: npm test --if-present

      - name: Build frontend
        working-directory: ./frontend/interview-pep
        run: npm run build --if-present

